config/routes.rb
Rails.application.routes.draw do

  root 'quotes#index'

  resources :quotes, only: [:index, :show, :create] do
    get 'random', on: :collection
    post 'update_likes', on: :collection
  end

  end

app/models/quote.rb
class Quote < ActiveRecord::Base

  scope :latest, -> { self.last }

  def missing_author_wallpaper
    google_image_keywords = ['san francisco city', 'chicago city', 'new york city', 'bora bora', 'top 10 exotic places']
    google_image_keywords.sample
  end

  def self.random
    ids = Quote.pluck(:id)
    quote = Quote.find(ids.sample)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def index
    ids = Quote.pluck(:id)
    @quote = Quote.random
  end

  def show
    @quote = Quote.find(params[:id])

    render 'index'
  end

  def random
    @quote = Quote.random

    respond_to do |format|
      format.html  { redirect_to root_path }
      format.json  { render json: @quote }
    end
  end

  def update_likes
    @quote = Quote.find(params[:id])
    @quote.likes = 0 if @quote.likes.blank?
    @quote.likes = @quote.likes+1

    if @quote.save!
      render json: @quote, status: :ok
    else
      render json: @quote, status: :unprocessable_entity
    end
  end

  def create
    @quote = Quote.new(quote_params)

    if @quote.save!
      redirect_to quote_path(@quote)
    end
  end

  private

    def quote_params
      params.require(:quote).permit(:description, :author, :likes)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Viadreams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container-fluid">
    <%= yield %>
  </div>

</body>
</html>

app/views/quotes/index.html.haml
= hidden_field_tag :author_name, @quote.author.blank? ? @quote.missing_author_wallpaper : @quote.author
= hidden_field_tag :quote_id, @quote.id

.background_cover
.row
  .col-md-10.col-xs-12
    .transparent_box
      / Header: title
      .row#quote_container_top
        .col-md-12.col-xs-12
          %h1#quote_title= "inspiration ##{@quote.id}"

      / Body: actual quote
      .row#quote_container_middle
        .col-md-12.col-xs-12
          %blockquote#quote_desc= @quote.description

      / Bottom: Author Name
      .row#quote_container_bottom
        .col-md-12.col-xs-12
          %p#quote_author= "~ #{@quote.author}" unless @quote.author.blank?

      / Bottom2: Likes
      .row#quote_container_last_bottom
        .col-md-12.col.xs-12
          %a.favIcon{href: "#"}
          %p.favIconNumber#quote_likes= @quote.likes.nil? ? 0 : @quote.likes
          = image_tag "viadreams_stamp_logo.png", class: "logo"

= render "quotes/partials/new_quote_modal"

app/views/quotes/partials/_new_quote_modal.html.haml
#newQuoteModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "newQuoteModalLabel", :role => "dialog", :tabindex => "-1"}
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} &times;
          %span.sr-only Close
        %h4#newQuoteModalLabel.modal-title New Quote
      .modal-body
        = form_for(:quote, url: quotes_path, remote: true) do |f|
          .form-group
            = f.text_area :description, placeholder: "Quote", value: '', class: "form-control", required: "required"
          .form-group
            = f.text_field :author, placeholder: "Author", value: '', class: "form-control"
          .modal-footer
            = f.submit "Save", class: "btn btn-primary"